development:
  secret_key_base: 'this-is-not-a-secret-97eb5ad29b493ac9f666fba282d75810'

test:
  secret_key_base: 'this-is-not-a-secret-97eb5ad29b493ac9f666fba282d75810'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
